version: '3'
services:
  mongo:
    image: baltig.infn.it:4567/chaos-lnf-control/chaos_bundle_compilation/mongo:3.4
    logging:
      driver: none

    ports:
      - "27017:27017"
      
  couchbase:
    image: couchbase/server:community-5.0.1
    logging:
      driver: none
    ports:
    - 8091:8091
    - 8092:8092
    - 8093:8093
    - 8094:8094
    - 11210:11210

  
  centos7_devel:
    stdin_open: true
    tty: true
    image: baltig.infn.it:4567/chaos-lnf-control/chaos_bundle_compilation:centos7
    depends_on:
          - couchbase
          - mongo
    ports:
    - "2222:22"

    environment:
          - "CHAOS_DB_SERVERS=mongo"
          - "EXTERNAL_DRIVER_SERVER=extdrv"
          - "CHAOS_LIVE_SERVERS=couchbase"
          
    volumes:
         - ../../../:/tmp/source
    command: /usr/sbin/sshd -D
