#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

module_path=$SCRIPTPATH
module_name=${SCRIPTPATH##*/}
repository_name="chaos-__chaos_project_type__-$module_name"


echo -e "\033[38;5;148m!CHAOS repository creation tools to LNF-Gerrit\033[39m"
echo -e "\033[38;5;148mModule path -> $module_path\033[39m"
echo -e "\033[38;5;148mModule name -> $module_name\033[39m"
echo -e "\033[38;5;148mRepository name -> $repository_name\033[39m"

cd $module_path

echo -e "\033[38;5;148mInitialize git\033[39m"
git init
touch README.md


cp __original_script_path__/gitignore_tmpl .gitignore

git add .
git commit -a -m "Initial commit"
git checkout -b development


echo "press any key to presist repo on gerrit lnf server"
read -n 1 -s
echo "Create repo on lnf gerrit server"
ssh -p 29418 cvs.lnf.infn.it gerrit create-project $repository_name
echo "simulation of gerrit creation of $repository_name"
if [ $? -gt 0 ]; then
	ssh -p 29418 cvs.lnf.infn.it gerrit set-project-parent --parent chaosframework  $repository_name
	git_repo_name="$repository_name.git"
	echo "Install lnf remote $git_repo_name"
		
	git remote add origin_ssh ssh://$user_name@cvs.lnf.infn.it:29418/$git_repo_name

	echo "upload to lnf git"
	git push origin_ssh master development
fi