#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

__chaos_cu_name__=$1
echo "!CHAOS Realt Time Control Unit creation tool"

if [ ! -n "$__chaos_cu_name__" ]; then
	echo "[FATAL]: the name of the control unit is mandatory"
	echo "Exiting script"
	exit 1
fi

echo "Start $__chaos_cu_name__ creation"

cu_dir="$SCRIPTPATH/../user_control_unit/"
if [ -d "$cu_dir/$__chaos_cu_name__" ]; then
	echo "[FATAL]: Control unit directory is alread present"
	echo "Exiting script"
	exit 1
fi

rm -rf $cu_dir
mkdir -p $cu_dir

echo "Create project files"
cp -r "$SCRIPTPATH/project_template/rtcu.tmpl"  $cu_dir
cd $cu_dir
mv rtcu.tmpl $__chaos_cu_name__

echo "rename project files"
cd $__chaos_cu_name__

cp $SCRIPTPATH/gitignore_tmpl .gitignore
sed -e "s/__chaos_project_type__/rtcu/g" $SCRIPTPATH/ChaosCreateOfficialRepository_tmpl > ChaosCreateOfficialRepository.sh


sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" CMakeLists_tmpl.txt > CMakeLists.txt
rm CMakeLists_tmpl.txt

mv __chaos_cu_name__.xcodeproj "$__chaos_cu_name__.xcodeproj"
sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" source/__chaos_cu_name__.cpp > "source/$__chaos_cu_name__.cpp"
rm source/__chaos_cu_name__.cpp

sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" source/__chaos_cu_name__.h > "source/$__chaos_cu_name__.h"
rm source/__chaos_cu_name__.h

sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" source/main.cpp > source/main_mod.cpp
rm source/main.cpp
mv source/main_mod.cpp source/main.cpp

echo "Patching xcode project"
cd "$__chaos_cu_name__.xcodeproj"
mv __chaos_cu_name__.xcscheme "$__chaos_cu_name__.xcscheme"
sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" project_tmpl.pbxproj > project.pbxproj
rm project_tmpl.pbxproj
