#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

__chaos_cu_name__=$1
cu_dir=$2
user_paths=1

echo "!CHAOS Real Time Control Unit creation tool"

if [ ! -n "$__chaos_cu_name__" ]; then
	echo "[FATAL]: the name of the control unit is mandatory"
	echo "Exiting ..."
	exit 1
fi

echo "Start $__chaos_cu_name__ creation"

if [ ! -n "$cu_dir" ]; then 
    cu_dir="$SCRIPTPATH/../user_control_unit/"
    user_paths=0
fi

if [ -d "$cu_dir/$__chaos_cu_name__" ]; then
	echo "[FATAL]: Control unit directory \"$cu_dir/$__chaos_cu_name__\" is already present"
	echo "Exiting..."
	exit 1
fi

# rm -rf $cu_dir
mkdir -p $cu_dir

echo "Create project files into $cu_dir/$__chaos_cu_name__"
cp -r "$SCRIPTPATH/project_template/rtcu.tmpl"  $cu_dir
cd $cu_dir
mv rtcu.tmpl $__chaos_cu_name__

echo "rename project files"
cd $__chaos_cu_name__

cp $SCRIPTPATH/gitignore_tmpl .gitignore
sed -e "s/__chaos_project_type__/rtcu/g" $SCRIPTPATH/ChaosCreateOfficialRepository_tmpl > ChaosCreateOfficialRepository.sh


sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" CMakeLists_tmpl.txt > CMakeLists.txt
rm CMakeLists_tmpl.txt

mv __chaos_cu_name__.xcodeproj "$__chaos_cu_name__.xcodeproj"
sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" source/__chaos_cu_name__.cpp > "source/$__chaos_cu_name__.cpp"
rm source/__chaos_cu_name__.cpp

sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" source/__chaos_cu_name__.h > "source/$__chaos_cu_name__.h"
rm source/__chaos_cu_name__.h

sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" source/main.cpp > source/main_mod.cpp
rm source/main.cpp
mv source/main_mod.cpp source/main.cpp

echo "Patching xcode project"
cd "$__chaos_cu_name__.xcodeproj"
mv __chaos_cu_name__.xcscheme "$__chaos_cu_name__.xcscheme"

if [[ -d "$CHAOS_FRAMEWORK" && $user_paths -eq 1 ]] ; then
tmpstr=`echo "$CHAOS_FRAMEWORK" | sed -e 's/\//\\\\\//g'`

sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" project_tmpl.pbxproj| sed "s/\$(SRCROOT)\/..\/../$tmpstr/g"  >project.pbxproj

else
sed -e "s/__chaos_cu_name__/$__chaos_cu_name__/g" project_tmpl.pbxproj > project.pbxproj
fi

rm project_tmpl.pbxproj
